/**
 * Alternatives Starter Pack (v1)
 *
 * Source: design/ux/alternatives_starter_pack_v1.md
 * 48 activities — 8 per trigger across 6 triggers.
 * IDs: sp_<TRIGGER>_<n>
 *
 * Note: No duration field (per spec).
 * Users can add/edit/delete/favorite later.
 */

import type { Activity } from './types';

const NOW = 0; // starter pack timestamps are epoch 0 (never "updated by user")

// --------------------------------------------------------------------------
// BOREDOM (8)
// --------------------------------------------------------------------------
const BOREDOM: Activity[] = [
    {
        id: 'sp_BOREDOM_1',
        title: 'Curiosity Question Trio',
        triggers: ['BOREDOM'],
        instructions:
            'Write 3 questions you\'re curious about right now. Pick 1 to explore later (not via scrolling).',
        isFavorite: false,
        source: 'STARTER_PACK',
        createdAt: NOW,
        updatedAt: NOW,
        tags: ['no_phone', 'creative', 'at_home'],
        phonePolicy: 'NO_PHONE',
        effort: 'LOW',
    },
    {
        id: 'sp_BOREDOM_2',
        title: 'Micro-Explore Outside',
        triggers: ['BOREDOM'],
        instructions:
            'Step outside and notice 5 specific details (colors, sounds, textures). Let your mind wander without input.',
        isFavorite: false,
        source: 'STARTER_PACK',
        createdAt: NOW,
        updatedAt: NOW,
        tags: ['outside', 'movement', 'no_phone', 'calm'],
        phonePolicy: 'NO_PHONE',
        effort: 'LOW',
    },
    {
        id: 'sp_BOREDOM_3',
        title: 'Learn One Small Thing (No Feeds)',
        triggers: ['BOREDOM'],
        instructions:
            'Choose one topic and read one focused page/article (no infinite scroll). Stop when done.',
        isFavorite: false,
        source: 'STARTER_PACK',
        createdAt: NOW,
        updatedAt: NOW,
        tags: ['learning', 'at_home', 'no_feed'],
        phonePolicy: 'INTENTIONAL_OK',
        effort: 'MEDIUM',
        notes: 'Use reader mode/bookmark; avoid feed platforms.',
    },
    {
        id: 'sp_BOREDOM_4',
        title: 'Make One Tiny Improvement',
        triggers: ['BOREDOM'],
        instructions: 'Improve one area: clear 10 items or wipe one surface.',
        isFavorite: false,
        source: 'STARTER_PACK',
        createdAt: NOW,
        updatedAt: NOW,
        tags: ['at_home', 'movement', 'practical', 'no_phone'],
        phonePolicy: 'NO_PHONE',
        effort: 'MEDIUM',
    },
    {
        id: 'sp_BOREDOM_5',
        title: 'Start a "2-Min Project Step"',
        triggers: ['BOREDOM'],
        instructions:
            'Pick a project (fitness, language, hobby). Do the smallest next step: set up materials, open notebook, prep.',
        isFavorite: false,
        source: 'STARTER_PACK',
        createdAt: NOW,
        updatedAt: NOW,
        tags: ['creative', 'at_home'],
        phonePolicy: 'NO_PHONE',
        effort: 'MEDIUM',
    },
    {
        id: 'sp_BOREDOM_6',
        title: 'Novelty Without Screens',
        triggers: ['BOREDOM'],
        instructions:
            'Change one variable (room, route, posture, silence). Let boredom reset attention naturally.',
        isFavorite: false,
        source: 'STARTER_PACK',
        createdAt: NOW,
        updatedAt: NOW,
        tags: ['calm', 'no_phone'],
        phonePolicy: 'NO_PHONE',
        effort: 'LOW',
    },
    {
        id: 'sp_BOREDOM_7',
        title: 'Read 2 Pages',
        triggers: ['BOREDOM'],
        instructions: 'Read 2 pages of a book. Stop after 2 pages if you want.',
        isFavorite: false,
        source: 'STARTER_PACK',
        createdAt: NOW,
        updatedAt: NOW,
        tags: ['calm', 'learning', 'at_home', 'no_phone'],
        phonePolicy: 'NO_PHONE',
        effort: 'LOW',
        notes: 'Needs item: book.',
    },
    {
        id: 'sp_BOREDOM_8',
        title: 'Creative Doodle / Sketch',
        triggers: ['BOREDOM'],
        instructions: 'Draw patterns/shapes for a moment. No goal — just expression.',
        isFavorite: false,
        source: 'STARTER_PACK',
        createdAt: NOW,
        updatedAt: NOW,
        tags: ['creative', 'calm', 'at_home', 'no_phone'],
        phonePolicy: 'NO_PHONE',
        effort: 'LOW',
        notes: 'Needs item: paper/pen.',
    },
];

// --------------------------------------------------------------------------
// STRESS_ANXIETY (8)
// --------------------------------------------------------------------------
const STRESS_ANXIETY: Activity[] = [
    {
        id: 'sp_STRESS_ANXIETY_1',
        title: 'Physiological Sigh ×3',
        triggers: ['STRESS_ANXIETY'],
        instructions:
            'Inhale → top-up inhale → long slow exhale. Repeat 3 times.',
        isFavorite: false,
        source: 'STARTER_PACK',
        createdAt: NOW,
        updatedAt: NOW,
        tags: ['calm', 'no_phone'],
        phonePolicy: 'NO_PHONE',
        effort: 'LOW',
    },
    {
        id: 'sp_STRESS_ANXIETY_2',
        title: 'Box Breathing',
        triggers: ['STRESS_ANXIETY'],
        instructions: '4 in → hold 4 → 4 out → hold 4. Repeat a few cycles.',
        isFavorite: false,
        source: 'STARTER_PACK',
        createdAt: NOW,
        updatedAt: NOW,
        tags: ['calm', 'no_phone'],
        phonePolicy: 'NO_PHONE',
        effort: 'LOW',
    },
    {
        id: 'sp_STRESS_ANXIETY_3',
        title: 'Grounding: 5–4–3–2–1',
        triggers: ['STRESS_ANXIETY'],
        instructions: 'Name 5 things you see, 4 feel, 3 hear, 2 smell, 1 taste.',
        isFavorite: false,
        source: 'STARTER_PACK',
        createdAt: NOW,
        updatedAt: NOW,
        tags: ['calm', 'no_phone'],
        phonePolicy: 'NO_PHONE',
        effort: 'LOW',
    },
    {
        id: 'sp_STRESS_ANXIETY_4',
        title: 'Write the Worry → Next Action',
        triggers: ['STRESS_ANXIETY'],
        instructions:
            'Write the worry in one sentence. Then write the next tiny action (even 1 minute).',
        isFavorite: false,
        source: 'STARTER_PACK',
        createdAt: NOW,
        updatedAt: NOW,
        tags: ['planning', 'at_home', 'no_phone'],
        phonePolicy: 'NO_PHONE',
        effort: 'MEDIUM',
    },
    {
        id: 'sp_STRESS_ANXIETY_5',
        title: 'Move to Discharge Stress',
        triggers: ['STRESS_ANXIETY'],
        instructions: '10 squats / quick stretch / short brisk walk.',
        isFavorite: false,
        source: 'STARTER_PACK',
        createdAt: NOW,
        updatedAt: NOW,
        tags: ['movement', 'outside', 'no_phone'],
        phonePolicy: 'NO_PHONE',
        effort: 'MEDIUM',
    },
    {
        id: 'sp_STRESS_ANXIETY_6',
        title: 'Tidy One Surface',
        triggers: ['STRESS_ANXIETY'],
        instructions:
            'Clear one small area (desk corner). Reduce visual noise; regain control.',
        isFavorite: false,
        source: 'STARTER_PACK',
        createdAt: NOW,
        updatedAt: NOW,
        tags: ['practical', 'at_home', 'no_phone'],
        phonePolicy: 'NO_PHONE',
        effort: 'MEDIUM',
    },
    {
        id: 'sp_STRESS_ANXIETY_7',
        title: 'Cold Water Reset',
        triggers: ['STRESS_ANXIETY'],
        instructions: 'Splash cold water on face or hold something cool briefly.',
        isFavorite: false,
        source: 'STARTER_PACK',
        createdAt: NOW,
        updatedAt: NOW,
        tags: ['calm', 'at_home', 'no_phone'],
        phonePolicy: 'NO_PHONE',
        effort: 'LOW',
    },
    {
        id: 'sp_STRESS_ANXIETY_8',
        title: 'Compassion Sentence',
        triggers: ['STRESS_ANXIETY'],
        instructions: '"This is hard. I\'m safe right now. One step at a time."',
        isFavorite: false,
        source: 'STARTER_PACK',
        createdAt: NOW,
        updatedAt: NOW,
        tags: ['calm', 'no_phone'],
        phonePolicy: 'NO_PHONE',
        effort: 'LOW',
    },
];

// --------------------------------------------------------------------------
// LONELINESS (8)
// --------------------------------------------------------------------------
const LONELINESS: Activity[] = [
    {
        id: 'sp_LONELINESS_1',
        title: 'Message One Person (Direct)',
        triggers: ['LONELINESS'],
        instructions: 'Send: "Hey, how are you? Want to talk later?"',
        isFavorite: false,
        source: 'STARTER_PACK',
        createdAt: NOW,
        updatedAt: NOW,
        tags: ['social'],
        phonePolicy: 'INTENTIONAL_OK',
        effort: 'LOW',
    },
    {
        id: 'sp_LONELINESS_2',
        title: 'Voice Note / Call',
        triggers: ['LONELINESS'],
        instructions:
            'Send a quick voice note or call for a few minutes. Keep it simple.',
        isFavorite: false,
        source: 'STARTER_PACK',
        createdAt: NOW,
        updatedAt: NOW,
        tags: ['social'],
        phonePolicy: 'INTENTIONAL_OK',
        effort: 'MEDIUM',
    },
    {
        id: 'sp_LONELINESS_3',
        title: 'Plan One Real Meet-up',
        triggers: ['LONELINESS'],
        instructions: 'Propose a concrete time/place (even short).',
        isFavorite: false,
        source: 'STARTER_PACK',
        createdAt: NOW,
        updatedAt: NOW,
        tags: ['social', 'planning'],
        phonePolicy: 'INTENTIONAL_OK',
        effort: 'MEDIUM',
    },
    {
        id: 'sp_LONELINESS_4',
        title: 'Go Where People Are',
        triggers: ['LONELINESS'],
        instructions:
            'Walk to a café/park/public place. You don\'t need to talk — just be around humans.',
        isFavorite: false,
        source: 'STARTER_PACK',
        createdAt: NOW,
        updatedAt: NOW,
        tags: ['outside', 'movement', 'social', 'no_phone'],
        phonePolicy: 'NO_PHONE',
        effort: 'MEDIUM',
    },
    {
        id: 'sp_LONELINESS_5',
        title: 'Small Act of Care',
        triggers: ['LONELINESS'],
        instructions:
            'Do one supportive action (encouraging message, small help).',
        isFavorite: false,
        source: 'STARTER_PACK',
        createdAt: NOW,
        updatedAt: NOW,
        tags: ['social'],
        phonePolicy: 'EITHER',
        effort: 'MEDIUM',
    },
    {
        id: 'sp_LONELINESS_6',
        title: 'Connection List',
        triggers: ['LONELINESS'],
        instructions:
            'List 5 people you can reach out to. Choose 1 and take the smallest step.',
        isFavorite: false,
        source: 'STARTER_PACK',
        createdAt: NOW,
        updatedAt: NOW,
        tags: ['planning', 'no_phone'],
        phonePolicy: 'NO_PHONE',
        effort: 'LOW',
    },
    {
        id: 'sp_LONELINESS_7',
        title: 'Nature / Pet Contact',
        triggers: ['LONELINESS'],
        instructions:
            'Spend a minute with a pet or outside in nature. Regulation first, then connection.',
        isFavorite: false,
        source: 'STARTER_PACK',
        createdAt: NOW,
        updatedAt: NOW,
        tags: ['calm', 'outside', 'no_phone'],
        phonePolicy: 'NO_PHONE',
        effort: 'LOW',
    },
    {
        id: 'sp_LONELINESS_8',
        title: 'Join a Scheduled Group',
        triggers: ['LONELINESS'],
        instructions:
            'Pick a recurring group (sport/class). Put one date on your calendar.',
        isFavorite: false,
        source: 'STARTER_PACK',
        createdAt: NOW,
        updatedAt: NOW,
        tags: ['social', 'planning'],
        phonePolicy: 'INTENTIONAL_OK',
        effort: 'MEDIUM',
    },
];

// --------------------------------------------------------------------------
// FATIGUE (8)
// --------------------------------------------------------------------------
const FATIGUE: Activity[] = [
    {
        id: 'sp_FATIGUE_1',
        title: 'Hydrate + Slow Breaths',
        triggers: ['FATIGUE'],
        instructions:
            'Drink water. Take 5 slow breaths to shift out of stimulation.',
        isFavorite: false,
        source: 'STARTER_PACK',
        createdAt: NOW,
        updatedAt: NOW,
        tags: ['calm', 'at_home', 'no_phone'],
        phonePolicy: 'NO_PHONE',
        effort: 'LOW',
    },
    {
        id: 'sp_FATIGUE_2',
        title: 'Eyes & Neck Reset',
        triggers: ['FATIGUE'],
        instructions:
            'Look far away for 20–30 seconds. Gently roll shoulders/neck.',
        isFavorite: false,
        source: 'STARTER_PACK',
        createdAt: NOW,
        updatedAt: NOW,
        tags: ['calm', 'movement', 'no_phone'],
        phonePolicy: 'NO_PHONE',
        effort: 'LOW',
    },
    {
        id: 'sp_FATIGUE_3',
        title: 'Power Rest (No Input)',
        triggers: ['FATIGUE'],
        instructions: 'Lie down, close eyes, and rest quietly. No content.',
        isFavorite: false,
        source: 'STARTER_PACK',
        createdAt: NOW,
        updatedAt: NOW,
        tags: ['calm', 'at_home', 'no_phone'],
        phonePolicy: 'NO_PHONE',
        effort: 'LOW',
    },
    {
        id: 'sp_FATIGUE_4',
        title: 'Light Walk / Daylight',
        triggers: ['FATIGUE'],
        instructions:
            'Go outside briefly. Daylight + movement helps reset fatigue.',
        isFavorite: false,
        source: 'STARTER_PACK',
        createdAt: NOW,
        updatedAt: NOW,
        tags: ['outside', 'movement', 'no_phone'],
        phonePolicy: 'NO_PHONE',
        effort: 'MEDIUM',
    },
    {
        id: 'sp_FATIGUE_5',
        title: 'Eat Something Simple',
        triggers: ['FATIGUE'],
        instructions:
            'If you haven\'t eaten, get a small balanced snack (protein + carbs).',
        isFavorite: false,
        source: 'STARTER_PACK',
        createdAt: NOW,
        updatedAt: NOW,
        tags: ['practical', 'at_home', 'no_phone'],
        phonePolicy: 'NO_PHONE',
        effort: 'LOW',
    },
    {
        id: 'sp_FATIGUE_6',
        title: 'Smallest Useful Thing',
        triggers: ['FATIGUE'],
        instructions:
            'Do one tiny task that reduces friction later (prep clothes, clear one item).',
        isFavorite: false,
        source: 'STARTER_PACK',
        createdAt: NOW,
        updatedAt: NOW,
        tags: ['practical', 'at_home', 'no_phone'],
        phonePolicy: 'NO_PHONE',
        effort: 'LOW',
    },
    {
        id: 'sp_FATIGUE_7',
        title: 'Reduce Input',
        triggers: ['FATIGUE'],
        instructions:
            'Lower lights, remove noise, sit quietly. Recovery needs less stimulation.',
        isFavorite: false,
        source: 'STARTER_PACK',
        createdAt: NOW,
        updatedAt: NOW,
        tags: ['calm', 'no_phone'],
        phonePolicy: 'NO_PHONE',
        effort: 'LOW',
    },
    {
        id: 'sp_FATIGUE_8',
        title: 'Early Night Setup',
        triggers: ['FATIGUE'],
        instructions:
            'Set up a better sleep environment (water by bed, dim lights, tidy bed).',
        isFavorite: false,
        source: 'STARTER_PACK',
        createdAt: NOW,
        updatedAt: NOW,
        tags: ['practical', 'calm', 'at_home', 'no_phone'],
        phonePolicy: 'NO_PHONE',
        effort: 'MEDIUM',
    },
];

// --------------------------------------------------------------------------
// SELF_DOUBT (8)
// --------------------------------------------------------------------------
const SELF_DOUBT: Activity[] = [
    {
        id: 'sp_SELF_DOUBT_1',
        title: 'Evidence List (3 Wins)',
        triggers: ['SELF_DOUBT'],
        instructions:
            'Write 3 things you did well (even small). Evidence beats feelings.',
        isFavorite: false,
        source: 'STARTER_PACK',
        createdAt: NOW,
        updatedAt: NOW,
        tags: ['calm', 'no_phone', 'at_home'],
        phonePolicy: 'NO_PHONE',
        effort: 'LOW',
    },
    {
        id: 'sp_SELF_DOUBT_2',
        title: 'One "Good Enough" Action',
        triggers: ['SELF_DOUBT'],
        instructions:
            'Pick one task and do the smallest "good enough" step. Confidence follows action.',
        isFavorite: false,
        source: 'STARTER_PACK',
        createdAt: NOW,
        updatedAt: NOW,
        tags: ['planning', 'practical', 'no_phone'],
        phonePolicy: 'NO_PHONE',
        effort: 'MEDIUM',
    },
    {
        id: 'sp_SELF_DOUBT_3',
        title: 'Reframe Sentence',
        triggers: ['SELF_DOUBT'],
        instructions:
            'Replace "I can\'t" with "I\'m learning / not yet." Then do one small step.',
        isFavorite: false,
        source: 'STARTER_PACK',
        createdAt: NOW,
        updatedAt: NOW,
        tags: ['calm', 'no_phone'],
        phonePolicy: 'NO_PHONE',
        effort: 'LOW',
    },
    {
        id: 'sp_SELF_DOUBT_4',
        title: 'Ask for One Clear Input',
        triggers: ['SELF_DOUBT'],
        instructions:
            'Message someone you trust: "Can you give me one quick perspective?" (No feeds.)',
        isFavorite: false,
        source: 'STARTER_PACK',
        createdAt: NOW,
        updatedAt: NOW,
        tags: ['social'],
        phonePolicy: 'INTENTIONAL_OK',
        effort: 'MEDIUM',
    },
    {
        id: 'sp_SELF_DOUBT_5',
        title: 'Self-Compassion Break',
        triggers: ['SELF_DOUBT'],
        instructions:
            '"This is hard. Others feel this too. May I be kind to myself right now."',
        isFavorite: false,
        source: 'STARTER_PACK',
        createdAt: NOW,
        updatedAt: NOW,
        tags: ['calm', 'no_phone'],
        phonePolicy: 'NO_PHONE',
        effort: 'LOW',
    },
    {
        id: 'sp_SELF_DOUBT_6',
        title: 'Review Past Proof',
        triggers: ['SELF_DOUBT'],
        instructions:
            'Look at past wins/good feedback you saved. Remind your brain with evidence.',
        isFavorite: false,
        source: 'STARTER_PACK',
        createdAt: NOW,
        updatedAt: NOW,
        tags: ['calm', 'at_home', 'no_feed'],
        phonePolicy: 'EITHER',
        effort: 'LOW',
        notes: 'Needs item: notes/files.',
    },
    {
        id: 'sp_SELF_DOUBT_7',
        title: 'Comparison Detox Decision',
        triggers: ['SELF_DOUBT'],
        instructions:
            'Name one account/feed that triggers doubt. Decide to avoid it today.',
        isFavorite: false,
        source: 'STARTER_PACK',
        createdAt: NOW,
        updatedAt: NOW,
        tags: ['planning', 'no_phone'],
        phonePolicy: 'NO_PHONE',
        effort: 'MEDIUM',
    },
    {
        id: 'sp_SELF_DOUBT_8',
        title: 'Tiny Skill Practice',
        triggers: ['SELF_DOUBT'],
        instructions:
            'Practice one micro-skill step (one paragraph, one rep, one example). Build confidence through reps.',
        isFavorite: false,
        source: 'STARTER_PACK',
        createdAt: NOW,
        updatedAt: NOW,
        tags: ['no_phone'],
        phonePolicy: 'NO_PHONE',
        effort: 'MEDIUM',
    },
];

// --------------------------------------------------------------------------
// NO_CLEAR_GOAL (8)
// --------------------------------------------------------------------------
const NO_CLEAR_GOAL: Activity[] = [
    {
        id: 'sp_NO_CLEAR_GOAL_1',
        title: 'Two-Minute Brain Dump',
        triggers: ['NO_CLEAR_GOAL'],
        instructions:
            'Write everything on your mind. Circle the one thing that matters most today.',
        isFavorite: false,
        source: 'STARTER_PACK',
        createdAt: NOW,
        updatedAt: NOW,
        tags: ['planning', 'no_phone', 'at_home'],
        phonePolicy: 'NO_PHONE',
        effort: 'MEDIUM',
    },
    {
        id: 'sp_NO_CLEAR_GOAL_2',
        title: 'Pick the Next Action',
        triggers: ['NO_CLEAR_GOAL'],
        instructions:
            'Choose one concrete next action you can do now. If it\'s big, shrink it.',
        isFavorite: false,
        source: 'STARTER_PACK',
        createdAt: NOW,
        updatedAt: NOW,
        tags: ['planning', 'practical', 'no_phone'],
        phonePolicy: 'NO_PHONE',
        effort: 'MEDIUM',
    },
    {
        id: 'sp_NO_CLEAR_GOAL_3',
        title: 'Top 3 Priorities (Next Few Hours)',
        triggers: ['NO_CLEAR_GOAL'],
        instructions: 'Write 3 priorities. Pick the smallest start on #1.',
        isFavorite: false,
        source: 'STARTER_PACK',
        createdAt: NOW,
        updatedAt: NOW,
        tags: ['planning', 'no_phone'],
        phonePolicy: 'NO_PHONE',
        effort: 'MEDIUM',
    },
    {
        id: 'sp_NO_CLEAR_GOAL_4',
        title: 'Values Check',
        triggers: ['NO_CLEAR_GOAL'],
        instructions:
            'Ask: "What matters today — health, relationships, work, learning?" Choose one aligned action.',
        isFavorite: false,
        source: 'STARTER_PACK',
        createdAt: NOW,
        updatedAt: NOW,
        tags: ['planning', 'calm', 'no_phone'],
        phonePolicy: 'NO_PHONE',
        effort: 'LOW',
    },
    {
        id: 'sp_NO_CLEAR_GOAL_5',
        title: 'If–Then Plan',
        triggers: ['NO_CLEAR_GOAL'],
        instructions:
            '"If I feel lost, then I will do ___ (one small action)."',
        isFavorite: false,
        source: 'STARTER_PACK',
        createdAt: NOW,
        updatedAt: NOW,
        tags: ['planning', 'no_phone'],
        phonePolicy: 'NO_PHONE',
        effort: 'LOW',
    },
    {
        id: 'sp_NO_CLEAR_GOAL_6',
        title: 'Clean Up One Thing',
        triggers: ['NO_CLEAR_GOAL'],
        instructions:
            'Do one small organizing task to reduce chaos and make goals easier to see.',
        isFavorite: false,
        source: 'STARTER_PACK',
        createdAt: NOW,
        updatedAt: NOW,
        tags: ['practical', 'at_home', 'no_phone'],
        phonePolicy: 'NO_PHONE',
        effort: 'LOW',
    },
    {
        id: 'sp_NO_CLEAR_GOAL_7',
        title: 'Ask Future Me',
        triggers: ['NO_CLEAR_GOAL'],
        instructions:
            'Imagine tomorrow morning: "What would I be glad I did today?" Do the smallest version.',
        isFavorite: false,
        source: 'STARTER_PACK',
        createdAt: NOW,
        updatedAt: NOW,
        tags: ['planning', 'no_phone'],
        phonePolicy: 'NO_PHONE',
        effort: 'MEDIUM',
    },
    {
        id: 'sp_NO_CLEAR_GOAL_8',
        title: 'One Commitment',
        triggers: ['NO_CLEAR_GOAL'],
        instructions:
            'Make one small commitment (send the email draft, open the document, set the appointment).',
        isFavorite: false,
        source: 'STARTER_PACK',
        createdAt: NOW,
        updatedAt: NOW,
        tags: ['planning', 'practical', 'no_phone'],
        phonePolicy: 'NO_PHONE',
        effort: 'MEDIUM',
    },
];

// --------------------------------------------------------------------------
// Combined export
// --------------------------------------------------------------------------

export const STARTER_PACK_ACTIVITIES: Activity[] = [
    ...BOREDOM,
    ...STRESS_ANXIETY,
    ...LONELINESS,
    ...FATIGUE,
    ...SELF_DOUBT,
    ...NO_CLEAR_GOAL,
];
